### ISSUE TITLE
Unformated output

### ISSUE THREAD

**Issue by tamirazrab** [cytopia/i3blocks-modules#17]
https://imgur.com/GpEUR4d can't seem to fix it, looked up at docs but couldn't find anything.

**Comment by cytopia** [comment]
Is this with all modules?

And did you set this line in your `~/.config/i3blocks/config`:
```
markup=pango
```

**Comment by tamirazrab** [comment]
I'm sorry for late response, I totally forgot about it, right after positing this issue, I tried with other modules and they all had the same kind of output however, after setting the `markup=pango` output is being properly formatted. Thanks!
